import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CourseService, Course } from '../../services/course.service'; // Adjust path if necessary
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-course-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './course-form.component.html', // Point to our new HTML file
  styleUrls: ['./course-form.component.scss'] // Point to our new SCSS file
})
export class CourseFormComponent {
  private courseService = inject(CourseService);
  course: Course = { id: 0, title: '', description: '' }; // Added ID for consistency, though it's typically generated by the backend
  isSubmitting: boolean = false;
  successMessage: string | null = null;
  errorMessage: string | null = null;

  submit() {
    this.isSubmitting = true;
    this.successMessage = null;
    this.errorMessage = null;

    this.courseService.create(this.course).subscribe({
      next: () => {
        this.successMessage = 'Course created successfully! You can now view it in the course list.';
        this.course = { id: 0, title: '', description: '' }; // Reset form after successful submission
        this.isSubmitting = false;
        // Optionally, clear success message after a few seconds
        setTimeout(() => this.successMessage = null, 5000);
      },
      error: (err) => {
        console.error('Error creating course:', err);
        this.errorMessage = 'Failed to create course. Please try again.';
        this.isSubmitting = false;
        // Optionally, clear error message after a few seconds
        setTimeout(() => this.errorMessage = null, 7000);
      }
    });
  }
}